'use strict';

window.TestGeneratorCypress = function (requests) {
  const lines = [
    "// Cypress API tests - generated by TestGenerator",
    "// npm install cypress",
    "",
    "describe('API tests from captured requests', () => {",
  ];
  requests.forEach((r, i) => {
    const method = (r.method || 'GET').toLowerCase();
    const url = r.url || '';
    const body = r.body ? tryParseBody(r.body) : null;
    const testName = sanitizeTestName(`${(r.method || 'GET').toUpperCase()} ${url}`) || `request_${i + 1}`;
    lines.push(`  it('${testName}', () => {`);
    const options = [];
    if (r.headers && Object.keys(r.headers).length) {
      options.push('headers: ' + JSON.stringify(r.headers));
    }
    if (body !== null && body !== undefined) {
      options.push('body: ' + (typeof body === 'object' ? JSON.stringify(body) : JSON.stringify(r.body)));
    }
    const opts = options.length ? ', { ' + options.join(', ') + ' }' : '';
    lines.push(`    cy.request('${method}', \`${url.replace(/`/g, '\\`')}\`${opts}).then((response) => {`);
    lines.push('      expect(response.status).to.be.oneOf([200, 201, 204]);');
    lines.push('    });');
    lines.push('  });');
    lines.push('');
  });
  lines.push('});');
  return lines.join('\n');
};

function tryParseBody(body) {
  if (typeof body === 'string') {
    try {
      return JSON.parse(body);
    } catch (_) {
      return body;
    }
  }
  return body;
}

function sanitizeTestName(name) {
  return name.replace(/[^a-zA-Z0-9\s_-]/g, ' ').replace(/\s+/g, ' ').trim().slice(0, 80) || 'request';
}
