'use strict';

window.TestGeneratorPlaywright = function (requests) {
  const lines = [
    "// Playwright API tests - generated by TestGenerator",
    "// npm install @playwright/test",
    "const { test, expect } = require('@playwright/test');",
    "",
    "test.describe('API tests from captured requests', () => {",
  ];
  requests.forEach((r, i) => {
    const method = (r.method || 'GET').toUpperCase();
    const url = escapeJsString(r.url || '');
    const body = r.body ? escapeJsString(r.body) : 'undefined';
    const testName = sanitizeTestName(`${method} ${r.url || 'request'}`) || `request_${i + 1}`;
    lines.push(`  test('${testName}', async ({ request }) => {`);
    lines.push(`    const response = await request.${method.toLowerCase()}(${url}, {`);
    if (r.headers && Object.keys(r.headers).length) {
      lines.push('      headers: ' + JSON.stringify(r.headers) + ',');
    }
    if (body !== 'undefined') {
      lines.push('      data: ' + body + ',');
    }
    lines.push('    });');
    lines.push('    expect(response.ok()).toBeTruthy();');
    lines.push('  });');
    lines.push('');
  });
  lines.push('});');
  return lines.join('\n');
};

function escapeJsString(s) {
  if (typeof s !== 'string') return '""';
  return JSON.stringify(s);
}

function sanitizeTestName(name) {
  return name.replace(/[^a-zA-Z0-9\s_-]/g, ' ').replace(/\s+/g, ' ').trim().slice(0, 80) || 'request';
}
