'use strict';

window.TestGeneratorRestAssured = function (requests) {
  const lines = [
    "// REST-assured tests - generated by TestGenerator",
    "// Add: io.rest-assured:rest-assured",
    "import org.junit.jupiter.api.Test;",
    "import static io.restassured.RestAssured.*;",
    "import static org.hamcrest.Matchers.*;",
    "",
    "public class ApiTests {",
    "",
  ];
  requests.forEach((r, i) => {
    const method = (r.method || 'GET').toUpperCase();
    const url = escapeJavaString(r.url || '');
    const testName = sanitizeMethodName(`${method}_${r.url || 'request'}`) || `request_${i + 1}`;
    lines.push('  @Test');
    lines.push(`  public void ${testName}() {`);
    lines.push('    given()');
    if (r.headers && Object.keys(r.headers).length) {
      Object.entries(r.headers).forEach(([k, v]) => {
        lines.push(`      .header("${escapeJavaString(k)}", "${escapeJavaString(String(v))}")`);
      });
    }
    if (r.body) {
      lines.push('      .body(' + escapeJavaString(r.body) + ')');
    }
    lines.push('    .when()');
    lines.push(`      .${method.toLowerCase()}(${url})`);
    lines.push('    .then()');
    lines.push('      .statusCode(anyOf(is(200), is(201), is(204)));');
    lines.push('  }');
    lines.push('');
  });
  lines.push('}');
  return lines.join('\n');
};

function escapeJavaString(s) {
  if (typeof s !== 'string') return '""';
  return '"' + s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n').replace(/\r/g, '\\r') + '"';
}

function sanitizeMethodName(name) {
  return name.replace(/[^a-zA-Z0-9_]/g, '_').replace(/_+/g, '_').slice(0, 80) || 'request';
}
